import "./globals.css";


export const metadata = {
  title: "Nusantara Collection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-bv" >{children}</body>
    </html>
  );
}
